# This is a basic workflow that is manually triggered

name: GasCheckWithAuth

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    # Inputs the workflow accepts.
    - cron: '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Send greeting
        env:
          super: ${{secrets.backend_rns}}
        run: curl -d '{"key":"$SECRET"}' -X GET https://rns-snowy.vercel.app/api/cron
